app:
  port: 8080
  env: dev
  name: template-backend
jwt:
  secret: 123456
  expires: 1000
  skip_auth_urls:
    - auth/login
database:
  host: 127.0.0.1:3306
  dbName: template
  account: remote_user
  password: RemoteUserPassword@123
