// Code generated by response_doc_gen.py. DO NOT EDIT.
package dto

import "template-backend/internal/model"

// HighSchoolAdmissionPlanResponseDoc 用于 Swagger 文档展示 (单对象返回)
type HighSchoolAdmissionPlanResponseDoc struct {
	Code    int                           `json:"code"`
	Msg     string                        `json:"msg"`
	Success bool                          `json:"success"`
	Data    model.HighSchoolAdmissionPlan `json:"data"`
}

// HighSchoolAdmissionPlanPageData 用于 Swagger 文档展示 (分页数据)
type HighSchoolAdmissionPlanPageData struct {
	List     []model.HighSchoolAdmissionPlan `json:"list"`
	Total    int64                           `json:"total"`
	Page     int                             `json:"page"`
	PageSize int                             `json:"pageSize"`
}

// HighSchoolAdmissionPlanPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type HighSchoolAdmissionPlanPageResponseDoc struct {
	Code    int                             `json:"code"`
	Msg     string                          `json:"msg"`
	Success bool                            `json:"success"`
	Data    HighSchoolAdmissionPlanPageData `json:"data"`
}

// LoginFormResponseDoc 用于 Swagger 文档展示 (单对象返回)
type LoginFormResponseDoc struct {
	Code    int             `json:"code"`
	Msg     string          `json:"msg"`
	Success bool            `json:"success"`
	Data    model.LoginForm `json:"data"`
}

// LoginFormPageData 用于 Swagger 文档展示 (分页数据)
type LoginFormPageData struct {
	List     []model.LoginForm `json:"list"`
	Total    int64             `json:"total"`
	Page     int               `json:"page"`
	PageSize int               `json:"pageSize"`
}

// LoginFormPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type LoginFormPageResponseDoc struct {
	Code    int               `json:"code"`
	Msg     string            `json:"msg"`
	Success bool              `json:"success"`
	Data    LoginFormPageData `json:"data"`
}

// UserInfoResponseDoc 用于 Swagger 文档展示 (单对象返回)
type UserInfoResponseDoc struct {
	Code    int            `json:"code"`
	Msg     string         `json:"msg"`
	Success bool           `json:"success"`
	Data    model.UserInfo `json:"data"`
}

// UserInfoPageData 用于 Swagger 文档展示 (分页数据)
type UserInfoPageData struct {
	List     []model.UserInfo `json:"list"`
	Total    int64            `json:"total"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
}

// UserInfoPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type UserInfoPageResponseDoc struct {
	Code    int              `json:"code"`
	Msg     string           `json:"msg"`
	Success bool             `json:"success"`
	Data    UserInfoPageData `json:"data"`
}

// LoginResponseResponseDoc 用于 Swagger 文档展示 (单对象返回)
type LoginResponseResponseDoc struct {
	Code    int                 `json:"code"`
	Msg     string              `json:"msg"`
	Success bool                `json:"success"`
	Data    model.LoginResponse `json:"data"`
}

// LoginResponsePageData 用于 Swagger 文档展示 (分页数据)
type LoginResponsePageData struct {
	List     []model.LoginResponse `json:"list"`
	Total    int64                 `json:"total"`
	Page     int                   `json:"page"`
	PageSize int                   `json:"pageSize"`
}

// LoginResponsePageResponseDoc 用于 Swagger 文档展示 (分页返回)
type LoginResponsePageResponseDoc struct {
	Code    int                   `json:"code"`
	Msg     string                `json:"msg"`
	Success bool                  `json:"success"`
	Data    LoginResponsePageData `json:"data"`
}

// ChangePasswordFormResponseDoc 用于 Swagger 文档展示 (单对象返回)
type ChangePasswordFormResponseDoc struct {
	Code    int                      `json:"code"`
	Msg     string                   `json:"msg"`
	Success bool                     `json:"success"`
	Data    model.ChangePasswordForm `json:"data"`
}

// ChangePasswordFormPageData 用于 Swagger 文档展示 (分页数据)
type ChangePasswordFormPageData struct {
	List     []model.ChangePasswordForm `json:"list"`
	Total    int64                      `json:"total"`
	Page     int                        `json:"page"`
	PageSize int                        `json:"pageSize"`
}

// ChangePasswordFormPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type ChangePasswordFormPageResponseDoc struct {
	Code    int                        `json:"code"`
	Msg     string                     `json:"msg"`
	Success bool                       `json:"success"`
	Data    ChangePasswordFormPageData `json:"data"`
}

// ConfigResponseDoc 用于 Swagger 文档展示 (单对象返回)
type ConfigResponseDoc struct {
	Code    int          `json:"code"`
	Msg     string       `json:"msg"`
	Success bool         `json:"success"`
	Data    model.Config `json:"data"`
}

// ConfigPageData 用于 Swagger 文档展示 (分页数据)
type ConfigPageData struct {
	List     []model.Config `json:"list"`
	Total    int64          `json:"total"`
	Page     int            `json:"page"`
	PageSize int            `json:"pageSize"`
}

// ConfigPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type ConfigPageResponseDoc struct {
	Code    int            `json:"code"`
	Msg     string         `json:"msg"`
	Success bool           `json:"success"`
	Data    ConfigPageData `json:"data"`
}

// LogResponseDoc 用于 Swagger 文档展示 (单对象返回)
type LogResponseDoc struct {
	Code    int       `json:"code"`
	Msg     string    `json:"msg"`
	Success bool      `json:"success"`
	Data    model.Log `json:"data"`
}

// LogPageData 用于 Swagger 文档展示 (分页数据)
type LogPageData struct {
	List     []model.Log `json:"list"`
	Total    int64       `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
}

// LogPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type LogPageResponseDoc struct {
	Code    int         `json:"code"`
	Msg     string      `json:"msg"`
	Success bool        `json:"success"`
	Data    LogPageData `json:"data"`
}

// MenuResponseDoc 用于 Swagger 文档展示 (单对象返回)
type MenuResponseDoc struct {
	Code    int        `json:"code"`
	Msg     string     `json:"msg"`
	Success bool       `json:"success"`
	Data    model.Menu `json:"data"`
}

// MenuPageData 用于 Swagger 文档展示 (分页数据)
type MenuPageData struct {
	List     []model.Menu `json:"list"`
	Total    int64        `json:"total"`
	Page     int          `json:"page"`
	PageSize int          `json:"pageSize"`
}

// MenuPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type MenuPageResponseDoc struct {
	Code    int          `json:"code"`
	Msg     string       `json:"msg"`
	Success bool         `json:"success"`
	Data    MenuPageData `json:"data"`
}

// MetaResponseDoc 用于 Swagger 文档展示 (单对象返回)
type MetaResponseDoc struct {
	Code    int        `json:"code"`
	Msg     string     `json:"msg"`
	Success bool       `json:"success"`
	Data    model.Meta `json:"data"`
}

// MetaPageData 用于 Swagger 文档展示 (分页数据)
type MetaPageData struct {
	List     []model.Meta `json:"list"`
	Total    int64        `json:"total"`
	Page     int          `json:"page"`
	PageSize int          `json:"pageSize"`
}

// MetaPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type MetaPageResponseDoc struct {
	Code    int          `json:"code"`
	Msg     string       `json:"msg"`
	Success bool         `json:"success"`
	Data    MetaPageData `json:"data"`
}

// PermissionResponseDoc 用于 Swagger 文档展示 (单对象返回)
type PermissionResponseDoc struct {
	Code    int              `json:"code"`
	Msg     string           `json:"msg"`
	Success bool             `json:"success"`
	Data    model.Permission `json:"data"`
}

// PermissionPageData 用于 Swagger 文档展示 (分页数据)
type PermissionPageData struct {
	List     []model.Permission `json:"list"`
	Total    int64              `json:"total"`
	Page     int                `json:"page"`
	PageSize int                `json:"pageSize"`
}

// PermissionPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type PermissionPageResponseDoc struct {
	Code    int                `json:"code"`
	Msg     string             `json:"msg"`
	Success bool               `json:"success"`
	Data    PermissionPageData `json:"data"`
}

// ResourceResponseDoc 用于 Swagger 文档展示 (单对象返回)
type ResourceResponseDoc struct {
	Code    int            `json:"code"`
	Msg     string         `json:"msg"`
	Success bool           `json:"success"`
	Data    model.Resource `json:"data"`
}

// ResourcePageData 用于 Swagger 文档展示 (分页数据)
type ResourcePageData struct {
	List     []model.Resource `json:"list"`
	Total    int64            `json:"total"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
}

// ResourcePageResponseDoc 用于 Swagger 文档展示 (分页返回)
type ResourcePageResponseDoc struct {
	Code    int              `json:"code"`
	Msg     string           `json:"msg"`
	Success bool             `json:"success"`
	Data    ResourcePageData `json:"data"`
}

// RoleResponseDoc 用于 Swagger 文档展示 (单对象返回)
type RoleResponseDoc struct {
	Code    int        `json:"code"`
	Msg     string     `json:"msg"`
	Success bool       `json:"success"`
	Data    model.Role `json:"data"`
}

// RolePageData 用于 Swagger 文档展示 (分页数据)
type RolePageData struct {
	List     []model.Role `json:"list"`
	Total    int64        `json:"total"`
	Page     int          `json:"page"`
	PageSize int          `json:"pageSize"`
}

// RolePageResponseDoc 用于 Swagger 文档展示 (分页返回)
type RolePageResponseDoc struct {
	Code    int          `json:"code"`
	Msg     string       `json:"msg"`
	Success bool         `json:"success"`
	Data    RolePageData `json:"data"`
}

// RoleResourceResponseDoc 用于 Swagger 文档展示 (单对象返回)
type RoleResourceResponseDoc struct {
	Code    int                `json:"code"`
	Msg     string             `json:"msg"`
	Success bool               `json:"success"`
	Data    model.RoleResource `json:"data"`
}

// RoleResourcePageData 用于 Swagger 文档展示 (分页数据)
type RoleResourcePageData struct {
	List     []model.RoleResource `json:"list"`
	Total    int64                `json:"total"`
	Page     int                  `json:"page"`
	PageSize int                  `json:"pageSize"`
}

// RoleResourcePageResponseDoc 用于 Swagger 文档展示 (分页返回)
type RoleResourcePageResponseDoc struct {
	Code    int                  `json:"code"`
	Msg     string               `json:"msg"`
	Success bool                 `json:"success"`
	Data    RoleResourcePageData `json:"data"`
}

// SchoolAdmissionInfoResponseDoc 用于 Swagger 文档展示 (单对象返回)
type SchoolAdmissionInfoResponseDoc struct {
	Code    int                       `json:"code"`
	Msg     string                    `json:"msg"`
	Success bool                      `json:"success"`
	Data    model.SchoolAdmissionInfo `json:"data"`
}

// SchoolAdmissionInfoPageData 用于 Swagger 文档展示 (分页数据)
type SchoolAdmissionInfoPageData struct {
	List     []model.SchoolAdmissionInfo `json:"list"`
	Total    int64                       `json:"total"`
	Page     int                         `json:"page"`
	PageSize int                         `json:"pageSize"`
}

// SchoolAdmissionInfoPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type SchoolAdmissionInfoPageResponseDoc struct {
	Code    int                         `json:"code"`
	Msg     string                      `json:"msg"`
	Success bool                        `json:"success"`
	Data    SchoolAdmissionInfoPageData `json:"data"`
}

// UserResponseDoc 用于 Swagger 文档展示 (单对象返回)
type UserResponseDoc struct {
	Code    int        `json:"code"`
	Msg     string     `json:"msg"`
	Success bool       `json:"success"`
	Data    model.User `json:"data"`
}

// UserPageData 用于 Swagger 文档展示 (分页数据)
type UserPageData struct {
	List     []model.User `json:"list"`
	Total    int64        `json:"total"`
	Page     int          `json:"page"`
	PageSize int          `json:"pageSize"`
}

// UserPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type UserPageResponseDoc struct {
	Code    int          `json:"code"`
	Msg     string       `json:"msg"`
	Success bool         `json:"success"`
	Data    UserPageData `json:"data"`
}

// UserCreateInformationResponseDoc 用于 Swagger 文档展示 (单对象返回)
type UserCreateInformationResponseDoc struct {
	Code    int                         `json:"code"`
	Msg     string                      `json:"msg"`
	Success bool                        `json:"success"`
	Data    model.UserCreateInformation `json:"data"`
}

// UserCreateInformationPageData 用于 Swagger 文档展示 (分页数据)
type UserCreateInformationPageData struct {
	List     []model.UserCreateInformation `json:"list"`
	Total    int64                         `json:"total"`
	Page     int                           `json:"page"`
	PageSize int                           `json:"pageSize"`
}

// UserCreateInformationPageResponseDoc 用于 Swagger 文档展示 (分页返回)
type UserCreateInformationPageResponseDoc struct {
	Code    int                           `json:"code"`
	Msg     string                        `json:"msg"`
	Success bool                          `json:"success"`
	Data    UserCreateInformationPageData `json:"data"`
}

// UserRoleResponseDoc 用于 Swagger 文档展示 (单对象返回)
type UserRoleResponseDoc struct {
	Code    int            `json:"code"`
	Msg     string         `json:"msg"`
	Success bool           `json:"success"`
	Data    model.UserRole `json:"data"`
}

// UserRolePageData 用于 Swagger 文档展示 (分页数据)
type UserRolePageData struct {
	List     []model.UserRole `json:"list"`
	Total    int64            `json:"total"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
}

// UserRolePageResponseDoc 用于 Swagger 文档展示 (分页返回)
type UserRolePageResponseDoc struct {
	Code    int              `json:"code"`
	Msg     string           `json:"msg"`
	Success bool             `json:"success"`
	Data    UserRolePageData `json:"data"`
}
