basePath: /api
definitions:
  dto.HighSchoolAdmissionPlanPageData:
    properties:
      list:
        items:
          $ref: '#/definitions/model.HighSchoolAdmissionPlan'
        type: array
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  dto.HighSchoolAdmissionPlanPageResponseDoc:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/dto.HighSchoolAdmissionPlanPageData'
      msg:
        type: string
      success:
        type: boolean
    type: object
  dto.HighSchoolAdmissionPlanResponseDoc:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/model.HighSchoolAdmissionPlan'
      msg:
        type: string
      success:
        type: boolean
    type: object
  model.HighSchoolAdmissionPlan:
    properties:
      ac_students:
        type: integer
      acd_students:
        type: integer
      admission_scope:
        type: string
      boarding_students:
        type: integer
      d_students:
        type: integer
      day_students:
        type: integer
      district_type:
        type: string
      id:
        type: integer
      operation_nature:
        type: string
      remarks:
        type: string
      school_level:
        type: string
      school_name:
        type: string
      total_students:
        type: integer
      year:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: template-backend管理系统的API文档
  title: template-backend API
  version: "1.0"
paths:
  /api/plans:
    get:
      consumes:
      - application/json
      description: 分页获取招生计划信息，支持条件筛选
      parameters:
      - description: 页码，默认1
        in: query
        name: page
        type: integer
      - description: 每页数量，默认10
        in: query
        name: page_size
        type: integer
      - description: 学校名称
        in: query
        name: school_name
        type: string
      - description: 年份
        in: query
        name: year
        type: integer
      - description: 区属类型
        in: query
        name: district_type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanPageResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanPageResponseDoc'
      summary: 获取招生计划列表
      tags:
      - 招生计划
    post:
      consumes:
      - application/json
      description: 新增一条招生计划记录
      parameters:
      - description: 招生计划对象
        in: body
        name: plan
        required: true
        schema:
          $ref: '#/definitions/model.HighSchoolAdmissionPlan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanResponseDoc'
      summary: 创建招生计划
      tags:
      - 招生计划
  /api/plans/{id}:
    delete:
      consumes:
      - application/json
      description: 根据ID删除招生计划
      parameters:
      - description: 招生计划ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanResponseDoc'
      summary: 删除招生计划
      tags:
      - 招生计划
    get:
      consumes:
      - application/json
      description: 根据ID获取招生计划详情
      parameters:
      - description: 招生计划ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanResponseDoc'
      summary: 获取单个招生计划详情
      tags:
      - 招生计划
    put:
      consumes:
      - application/json
      description: 根据ID更新招生计划信息
      parameters:
      - description: 招生计划ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新内容
        in: body
        name: plan
        required: true
        schema:
          $ref: '#/definitions/model.HighSchoolAdmissionPlan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HighSchoolAdmissionPlanResponseDoc'
      summary: 更新招生计划
      tags:
      - 招生计划
swagger: "2.0"
